name: Buf Lint & Breaking Check

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  buf-check:
    name: Run Buf Lint & Breaking
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Buf
        uses: bufbuild/buf-setup-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Buf Lint
        run: buf lint

      - name: Buf Breaking
        run: buf breaking --against '.git#branch=main'
