name: Buf CI Pipeline

on:
  push:
    branches:
      - 'release/**'
  pull_request:

permissions:
  contents: write

jobs:
  lint-breaking:
    name: Buf Lint & Breaking
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Buf CLI
        uses: bufbuild/buf-setup-action@v1

      - name: Buf Lint
        run: buf lint

      - name: Buf Breaking
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          AUTHED_URL="https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/orjinfinity/suit-proto.git"
          buf breaking --against "$AUTHED_URL#branch=main"

  generate:
    name: Buf Generate Code
    runs-on: ubuntu-latest
    needs: lint-breaking

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Buf CLI
        uses: bufbuild/buf-setup-action@v1

      - name: Generate Code
        run: |
          # Make generate çalıştır
          make generate
          
          # Dosyaların varlığını kontrol et
          echo "=== Generated files check ==="
          ls -la gen/
          
          # Cargo.toml ve go.mod dosyalarının varlığını kontrol et
          if [ ! -f "Cargo.toml" ] || [ ! -f "go.mod" ] || [ ! -f "go.sum" ]; then
            echo "Warning: Some dependency files are missing"
            # Eğer scripts klasöründe varsa kopyala
            [ -f "scripts/Cargo.toml" ] && cp scripts/Cargo.toml ./
            [ -f "scripts/go.mod" ] && cp scripts/go.mod ./
            [ -f "scripts/go.sum" ] && cp scripts/go.sum ./
          fi

      - name: Upload generated code and dependencies
        uses: actions/upload-artifact@v4
        with:
          name: generated-code
          path: |
            gen/**/*
            Cargo.toml
            go.mod
            go.sum

  publish:
    name: Publish & Git Tag
    runs-on: ubuntu-latest
    needs: generate

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download generated code
        uses: actions/download-artifact@v4
        with:
          name: generated-code
          path: downloaded-artifacts

      - name: Move files to correct locations
        run: |
          echo "=== Before moving files ==="
          ls -la downloaded-artifacts/
          
          # Gen klasörünü taşı
          rm -rf gen
          mv downloaded-artifacts/gen ./
          
          # Kök dizin dosyalarını taşı (hata kontrolü ile)
          for file in Cargo.toml go.mod go.sum; do
            if [ -f "downloaded-artifacts/$file" ]; then
              mv "downloaded-artifacts/$file" ./
              echo "Moved $file successfully"
            else
              echo "Warning: $file not found in artifacts"
            fi
          done
          
          # Geçici dizini temizle
          rm -rf downloaded-artifacts
          
          echo "=== After moving files ==="
          ls -la

      - name: Extract tag from branch name
        run: |
          branch_name=${GITHUB_REF##*/}
          tag_name="v${branch_name#release/}"
          echo "Detected tag: $tag_name"
          echo "$tag_name" > VERSION
          echo "tag=$tag_name" >> $GITHUB_ENV

      - name: Prepare Release Assets
        run: |
          # Dosyaların varlığını kontrol et
          for file in gen/ Cargo.toml go.mod go.sum VERSION; do
            if [ -e "$file" ]; then
              echo "$file exists"
            else
              echo "Warning: $file is missing"
            fi
          done
          
          # Zip oluştur
          zip -r generated-code.zip gen/ Cargo.toml go.mod go.sum VERSION
          
          # Debug için içeriği kontrol et
          echo "=== Zip içeriği ==="
          unzip -l generated-code.zip

      - name: Create Git Tag
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag -f ${{ env.tag }}
          git push origin --force ${{ env.tag }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.tag }}
          files: |
            generated-code.zip
            Cargo.toml
            go.mod
            go.sum
            VERSION
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Cleanup
        if: always()
        run: |
          rm -f generated-code.zip