name: Buf Generate

on:
  workflow_run:
    workflows: ["Buf Lint & Breaking Check"]
    types:
      - completed

jobs:
  generate-code:
    name: Buf Generate for Go, Rust, TS, gRPC-Web
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Buf CLI
        uses: bufbuild/buf-setup-action@v1

      - name: Generate Code
        run: buf generate

      - name: Upload generated code as artifact
        uses: actions/upload-artifact@a1fbd6d62b78583c2cfc365d3b6e664e256f318e
        with:
          name: generated-code
          path: |
            gen/go
            gen/rust
            gen/ts
            gen/grpc-web