name: Publish SDK to GitHub NPM Registry

on:
  push:
    branches:
      - main

jobs:
  publish-npm:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        dir: [gen/ts, gen/grpc-web]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://npm.pkg.github.com/

      - name: Publish ${{ matrix.dir }}
        working-directory: ${{ matrix.dir }}
        run: |
          npm version patch
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
